<?php

namespace App\Http\Controllers;

use App\Models\AnomalyReview;
use App\Models\BacklogItem;
use App\Models\Enquiry;
use App\Models\Process;
use App\Services\AnomalyService;
use App\Services\EnquiryCopilotService;
use App\Services\LlmService;
use App\Services\ReportingService;
use App\Services\TriageService;
use App\Services\UrsDrafterService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AiController extends Controller
{
    public function overview(LlmService $llm)
    {
        return view('ai.overview', ['aiLive' => $llm->enabled()]);
    }

    /* ── Billing anomaly detection ─────────────────── */
    public function anomalies(AnomalyService $svc, LlmService $llm)
    {
        $flags = $svc->scan();
        return view('ai.anomalies', [
            'flags' => $flags->take(20),
            'summary' => $svc->summary($flags),
            'byRule' => $flags->groupBy('rule')->map->count(),
            'aiLive' => $llm->enabled(),
        ]);
    }

    public function explainAnomaly(Request $r, AnomalyService $svc)
    {
        $flags = $svc->scan();
        $f = $flags->first(fn ($x) => $x['subject_type'] === $r->query('type') && (string) $x['subject_id'] === (string) $r->query('id') && $x['rule'] === $r->query('rule'));
        abort_unless($f, 404);
        return back()->with('explain_key', "{$r->query('type')}:{$r->query('id')}:{$r->query('rule')}")
                     ->with('explain_text', $svc->explain($f));
    }

    public function reviewAnomaly(Request $r)
    {
        $data = $r->validate([
            'subject_type' => 'required|in:bill,adjustment',
            'subject_id'   => 'required|integer',
            'rule'         => 'required|string',
            'verdict'      => 'required|in:confirmed,dismissed',
        ]);
        AnomalyReview::updateOrCreate(
            ['subject_type' => $data['subject_type'], 'subject_id' => $data['subject_id'], 'rule' => $data['rule']],
            ['verdict' => $data['verdict']]
        );
        $msg = $data['verdict'] === 'confirmed'
            ? "Anomaly confirmed and raised as a correction task for the billing team (AI proposed, human decided)."
            : "Anomaly dismissed as a false positive — recorded.";
        return back()->with('ok', $msg);
    }

    public function exportAnomalies(AnomalyService $svc)
    {
        $flags = $svc->scan();
        $csv = "severity,rule,subject_type,subject_id,review,finding\n";
        foreach ($flags as $f) {
            $csv .= implode(',', [
                $f['severity'], $f['rule'], $f['subject_type'], $f['subject_id'], $f['review'] ?? 'open',
                '"' . str_replace('"', '""', $f['reason']) . '"',
            ]) . "\n";
        }
        return response($csv, 200, [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename="billing-anomalies.csv"',
        ]);
    }

    /* ── URS / gap drafter ─────────────────────────── */
    public function urs(Request $r, UrsDrafterService $svc, LlmService $llm)
    {
        $gaps = Process::whereIn('coverage', ['gap', 'enhancement'])
            ->orderByRaw("coverage='gap' desc")->orderBy('module_code')->limit(400)->get();
        $selected = $r->query('p') ? Process::find($r->query('p')) : null;
        $draft = $selected ? $svc->draft($selected) : null;
        $modules = $gaps->pluck('module_code')->unique()->values();
        return view('ai.urs', compact('gaps', 'selected', 'draft', 'modules') + ['aiLive' => $llm->enabled()]);
    }

    public function ursExport(Process $process, UrsDrafterService $svc)
    {
        $d = $svc->draft($process);
        $md = "# {$d['title']}\n\n`{$d['ref']}` · module {$d['module']} · IWK grade: {$d['grade']}\n\n"
            . "## 1. Purpose\n{$d['purpose']}\n\n## 2. Scope\n" . $this->bullets($d['scope'])
            . "\n## 3. Functional Requirements\n" . $this->bullets($d['functional'])
            . "\n## 4. Integration\n" . $this->bullets($d['integration'])
            . "\n## 5. Non-Functional\n" . $this->bullets($d['nonfunctional'])
            . "\n## 6. Acceptance Criteria\n" . $this->bullets($d['acceptance'])
            . "\n## 7. Open Items (4–5 Aug access window)\n" . $this->bullets($d['open'])
            . "\n\n_Draft for BA review — not a final signed URS. Generated by the NBS URS/Gap Drafter._\n";
        return response($md, 200, [
            'Content-Type' => 'text/markdown',
            'Content-Disposition' => 'attachment; filename="' . $d['ref'] . '.md"',
        ]);
    }

    public function ursBatch(Request $r, UrsDrafterService $svc)
    {
        $code = $r->query('module');
        $procs = Process::where('module_code', $code)->whereIn('coverage', ['gap', 'enhancement'])->get();
        abort_if($procs->isEmpty(), 404);
        $md = "# URS drafts — {$code} module\n\n" . $procs->count() . " gap/enhancement processes.\n\n";
        foreach ($procs as $p) {
            $d = $svc->draft($p);
            $md .= "\n---\n\n## {$d['title']}\n`{$d['ref']}` · IWK grade: {$d['grade']}\n\n"
                . "**Purpose.** {$d['purpose']}\n\n**Functional requirements:**\n" . $this->bullets($d['functional']);
        }
        return response($md, 200, [
            'Content-Type' => 'text/markdown',
            'Content-Disposition' => 'attachment; filename="URS-drafts-' . $code . '.md"',
        ]);
    }

    private function bullets(array $xs): string
    {
        return implode("\n", array_map(fn ($x) => "- $x", $xs)) . "\n";
    }

    /* ── Enquiry copilot ───────────────────────────── */
    public function enquiryCopilot(Request $r, EnquiryCopilotService $svc, LlmService $llm)
    {
        $text = $r->query('text');
        $result = null;
        if ($text) {
            $stub = new Enquiry(['no' => 'ENQ-DEMO', 'channel' => 'call']);
            $result = ['text' => $text, 'classify' => $svc->classify($text), 'reply' => $svc->draftReply($stub, $text)];
        }
        // deepen: classify the real open enquiry records too
        $live = Enquiry::with('account')->where('status', '!=', 'resolved')->limit(6)->get()
            ->map(fn ($e) => ['e' => $e, 'c' => $svc->classify($e->category . ' ' . $e->detail)]);
        $samples = [
            'My bill this month is RM 240, usually I only pay RM 8. This is wrong, please check.',
            'I already paid last week but the account still shows outstanding. Payment not reflected.',
            'How do I register for e-bill / paperless billing by email?',
        ];
        return view('ai.enquiry', compact('result', 'samples', 'live') + ['aiLive' => $llm->enabled()]);
    }

    /* ── Assessment triage (NEW) ───────────────────── */
    public function triage(Request $r, TriageService $svc, LlmService $llm)
    {
        $module = $r->query('module');
        $q = BacklogItem::query()->when($module, fn ($w) => $w->where('module_code', $module))
            ->orderByRaw("triage_state='pending' desc")->orderByDesc('confidence');
        return view('ai.triage', [
            'items' => $q->limit(40)->get(),
            'summary' => $svc->summary(),
            'modules' => BacklogItem::select('module_code')->distinct()->pluck('module_code'),
            'module' => $module,
            'classes' => TriageService::CLASSES,
            'floor' => TriageService::CONFIDENCE_FLOOR,
            'aiLive' => $llm->enabled(),
        ]);
    }

    public function runTriage(TriageService $svc)
    {
        $n = $svc->classifyPending();
        return back()->with('ok', "AI classified {$n} backlog items — each proposed with a confidence score, awaiting engineer confirmation.");
    }

    public function confirmTriage(Request $r, BacklogItem $item, TriageService $svc)
    {
        $svc->confirm($item, $r->input('override'));
        return back()->with('ok', "{$item->jira_key} " . ($item->triage_state === 'overridden' ? 'overridden' : 'confirmed') . " by engineer — counts as scope.");
    }

    /* ── NL reporting (NEW) ────────────────────────── */
    public function reporting(Request $r, ReportingService $svc, LlmService $llm)
    {
        $question = $r->query('q');
        $result = $question ? $svc->answer($question) : null;
        return view('ai.reporting', [
            'question' => $question,
            'result' => $result,
            'aiLive' => $llm->enabled(),
            'samples' => ['Total outstanding by period', 'Receipts by method', 'Top debtors', 'Arrears aging', 'Bills this period', 'Accounts by category'],
        ]);
    }
}
